/*
 * CDR API
 *
 * Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveCdrApiClient

type ProblemDetails struct {
	Type_ string `json:"type,omitempty"`
	Title string `json:"title,omitempty"`
	Status int32 `json:"status,omitempty"`
	Detail string `json:"detail,omitempty"`
	Instance string `json:"instance,omitempty"`
}
